name: Alles over (UX) User Experience Design
favicon: null
layout_spectrum: 0.7377370547037572
typography_spectrum: 0.32575922831892967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3786262811627239
  lightness: 0.5421132394112647
  saturation: 0.149123914539814
  rhythmicContrast: 0.5823812421876937
purpose: []
